# Site Settings
lang: en
title: Data-cloud
tagline: Advanced Data Structures and Algorithms
description: >
  A learning platform providing resources and materials for Advanced Data Structures and Algorithms.
baseurl: "/Data-cloud02"
url: "https://adbms620.github.io/Data-cloud02/"
permalink: pretty
#favicon: /path/to/favicon.png
#theme_color: '#004488'
#fixed_navbar: top
force_theme: light

paginate: 5
paginate_path: "/blog/page:num"


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

# Google Analytics (Optional)
# google_analytics: UA-code-here

cookie_policy: /cookie-policy/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Data-Cloud"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: data_cloud_footer_menu

# Collections (For organizing content)
collections:
  materials: 
    output: true
    layout: material
    show_sidebar: true
  tutorials:
    output: true
    layout: tutorial
    show_sidebar: true





